### PR TITLE
Translation should really work now

### PR DESCRIPTION
**Pull request by WloBeb**

### CODE REVIEW

**Comment by WloBeb** [comment]
@noonereally I have one little questions:
Why most of your commits have no description? Eg. have only description "Update main.js"

**Comment by GeneralSheppard** [comment]
Thank you for this.
As soon as I get home I start working on it.

**Comment by noonereally** [comment]
The "Update main.js" is the default, so some are minor fixes, from css change to minor bug, like for example that missing vendorPots5 (there is another one missing, that I will commit soon). 
Others i just forget and commit. 
I'll try to be more descriptive in the future. 

With the translation function needs the setting, can I just put the setting loading higher ? And the translation call after it.
And maybe only read do GM_getValue only if !scriptSettngs.
Just a though, I'm scared of those GM_loads.

btw, where is the "+" I went over your branches and can't find it.
I want to add custom/private profiles tab and wanted to merge that idea.. with an option to import profiles and save into the GM_setValue. 
-- I know it was long ago, yet I was busy and didn't have the time, also to be honest at a glance I'm not sure 100% how both the functions work exactly so merging it in a good way will take digging and testing so I delayed it.

**Comment by WloBeb** [comment]
You really didn't use local git repository on your computer???

With regards to reading scriptSettings.
Just look at code. When you read settings, you merge it with setting object, which includes names displayed on interface, witch should be translated, witch needs language variable from stored settings.....  insane circle.
The only solution that came to my mind, is a self-reading of script setting object (only once).
Another idea is redundant GM_ variable that stores only language.

BTW. Do you know, that enable/disable debug doesn't work? Everything is <b>always</b> logged on real console. Probably "onsave" part doesn't work.

"+" is in my <a href=https://github.com/WloBeb/NW-Profession-Bot/tree/list_idea_concatenation>list idea</a> branch. But this branch is really obsolete.
I have yet another idea, never implemented.

<pre><code>    function createNextTask(prof, i, <b><i>level</i></b>) {</code></pre>

 if 'level' === undefined get profession level of current character (as now)
and inside:

<pre><code>        if (list.length <= i) {
            <s>console.log("Nothing Found");</s>
            <s>switchChar();</s>
            <s>return false;</s>
            <b><i>createNextTask(prof, 0, level-1);</i></b>
        }</code></pre>

**Comment by noonereally** [comment]
No, I just paste and commit here.

Things in the settings object never displayed to the user. 
The displayed part is at settingsUI array. And the actual display part is at the bottom of the execution, at process()

Yes, thanks, there is a unsafewindow.console = console hard coded line for now, the onsave thing is problematic.

Need to look at the code.

**Pull request merged**
