### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by WloBeb**
Change naming convention to better understanding and place where the character name is read

### CODE REVIEW

**Comment by noonereally** [comment]
If you add your changes to the version and contributes / developers part, i'll be happy to merge to give you credit. I thought this fork will be a pull request and someone else will take care of all the version stuff on merge but it is not merged for a long time.

**Comment by Phr33d0m** [comment]
It will be, soon, very soon! I've been going through your closed pull-reqs to see what other changes aside from yours have been made, just to keep track of things.

**Comment by noonereally** [comment]
When i tried to pull request and it complained about the merge problem i've merged the changes by mac-nw manually, so there are many changes by him that should be credited (his commits to the main branch).

**Comment by Phr33d0m** [comment]
I merged it a couple of hours ago, there were quite a bit of stupid conflicts but well, doesn't matter.

**Pull request merged**
