### PR TITLE
Adjusted crafting professions.

### PR DESCRIPTION
**Pull request by dlebedynskyi**
Created profile for crafting stuff. Jewelcrafting and some Leatherworking. 
Added fallback for Alchemy so that it won't be stuck waiting for 1 slot with some slots open.

### CODE REVIEW

**Comment by RottenMind** [comment]
Just reminder MOD6 not only raise character level all profession will rank up LvL25,

Here is, list I use on current script,
https://gist.github.com/RottenMind/c331cbed76e3df2738c6

Leadership new task and rares are here, 28.2.2015 from preview server, more info from Wiki  http://neverwinter.gamepedia.com/Leadership

```
LVL:21 ,name:"Protect Magical Goods Market" taskname:"Leadership_Tier4_21_Protectmagic".
LVL:21 ,name:"Train for the Protector's Tourney" taskname:"Leadership_Tier4_21_Training".
LVL:22 ,name:"Guard Clerics of Ilmater" taskname:"Leadership_Tier4_22_Guardclerics".
LVL:23 ,name:"Guard Young Noble on Trip" taskname:"Leadership_Tier4_23_Guardnoble". 
LVL:24 ,name:"Escort a Wizard's Seneschal" taskname:"Leadership_Tier4_24_Wizardsseneschal". 
LVL:25 ,name:"Battle Elemental Cultists" taskname:"Leadership_Tier4_25_Battleelementalcultists". 

LVL:21 ,name:"Kill Rogue Elemental" taskname:"Leadership_Tier4_21r_Killelemental". 
LVL:22 ,name:"Capture Bandit Leader" taskname:"Leadership_Tier4_22r_Capturebandithq".
LVL:23 ,name:"Provide security for Pilgrims" taskname:"Leadership_Tier4_23r_Securepilgrimage".
LVL:24 ,name:"Kill a young Dragon" taskname:"Leadership_Tier4_24r_Killdragon".
LVL:25 ,name:"Hunt down an escaped Experiment" taskname:"Leadership_Tier4_25r_Huntexperiment".
```

Check conversation below,
http://nw-forum.perfectworld.com/showthread.php?850351-severe-reduction-ahead-in-AD-gained-through-leadership/page5

Alchemy get just few new "experiments" up lvl25 and few new potions, this task needs some change to script,
- "Alchemy_Tier4_Aquaregia_2"

Similar task with "Empowered Aquavitae" so script must know to use more efficient task. (solved allredy, and seems work on previewserver)

```
 // Use more efficient Empowered task for Aqua Vitae/Aqua Regia if available.
    if (searchItem == "Crafting_Resource_Aquavitae" || "Crafting_Resource_Aquaregia" && taskList.length > 1) {
        taskList.shift();
    }
    /*if (searchItem == "Crafting_Resource_Aquaregia" && taskList.length > 1) { // no needed
        taskList.shift();
    }*/
```

Other professions will get level up to 25 too, but basic leveling should be done with "old jobs" because new tasks use quite "expensive and rare" materials. Check preview server for more recent changes.

So if Gateway itself stays as it is then mod6 will not cause too much changes.

**Comment by dlebedynskyi** [comment]
This changes are just for current levels. For now I just separated them in new profile. I was looking at new professions. Right now task on  purple level are fairly balanced with resources they use. Having 1 char running 3-5 leadership tasks on resource profile gives enough supplies to keep at least 1 craft profile running.  Only one consumable I feed for them is eggs. Running pretty solid for 2 weeks ~ > 100k profit per one craft task /day after selling items on AH. Usually task runs at least 2 crafting profs a day. 

I ll be looking at new tasks soon. The only question is really how rare are items. Im not so worried about AD reduction - we can not get away with this. But how often new "Enchanted Coffer" will be dropping good resources - this is what concerns me. 

Also might be a good idea to create profile for refinement items. Also depends on drop chances.

What I would really like to see is char specific priorities  on same prof by profile - so that we could assign 3 slots with high priority for craft, 3 with medium for AD and 2 for RP. This would remove a lot of micro management per char.

edit: also look at this http://nw-forum.perfectworld.com/showthread.php?851501-The-positives-of-the-leadership-changes&p=10243041&viewfull=1#post10243041

It seems not all professions are listed yet.

**Comment by RottenMind** [comment]
It seems that all professions has lvl25.(previewserver 6.3.2015)

...and Leadership has 5 new Rare + 6 new common task, Wiki page is not yet updated task completion times, but it seems to be easy separate AD and "RP/XP" -line so I dont need maintain multiple profiles  per profession (maybe later), ;).

...maybe I need extract profession names and update http://pastebin.com/VaGntEha  Task Name Maps, only "Rares" are harder to catch.

EDIT, I started it. Its based http://pastebin.com/VaGntEha -list and current preview professions, most NEW (mod4 -6) rares are not included, but they can be added later,

## http://pastebin.com/inR0Hwv0

**Comment by dlebedynskyi** [comment]
yeah. we need to maintain those profiles easier. It looks to be a bit too much to keep 25 levels for each. Ill  start looking at those task over lvl 20 for profession i know of. 
I think we can safely start doing 
https://gist.github.com/RottenMind/c331cbed76e3df2738c6

as a start for now. new mod is close. so lets get it test start

**Pull request merged**
